# Generated by Django 5.1.7 on 2025-06-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'other')], default='male'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medicine_detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_visit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
