# Generated by Django 5.1.7 on 2025-06-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_age_patient_amount_patient_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
